name: hsca
description: Ensuring every corner of your home is checked, for peace of mind and comfort.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.1
  email_validator: ^2.1.17
  csc_picker: ^0.2.7
  country_picker:
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.18
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7
  responsive_framework: ^0.2.0
  responsive_table: ^0.2.0+2
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  injectable:  ^1.5.0
  retrofit: ^4.0.1
  auto_route: ^5.0.4
  flutter_bloc: ^7.3.3
  json_annotation: ^4.8.0
  dio: ^5.0.2
  percent_indicator: ^4.2.3
  flutter_svg:
  intl: ^0.18.0
  ndialog: ^4.2.2
  shimmer: ^2.0.0
  awesome_dialog: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  auto_route_generator:
  injectable_generator:
  retrofit_generator:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/


  # command to create all generated files like, model classes, routers, retrofit classes
  # ------  flutter pub run build_runner build --delete-conflicting-outputs
